# This is a config for E2B sandbox template.
# You can use template ID (sh4267qdwkyu8vb834jb) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("sh4267qdwkyu8vb834jb") # Sync sandbox
# sandbox = await AsyncSandbox.create("sh4267qdwkyu8vb834jb") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('sh4267qdwkyu8vb834jb')

team_id = "15fb2e03-402b-4cf1-8512-38a63604584b"
start_cmd = "python /app/gridagent_server.py"
dockerfile = "Dockerfile"
template_id = "sh4267qdwkyu8vb834jb"
